### ISSUE TITLE
Cannot add extension with name 'googleServices', as there is an extension already registered with that name.

### ISSUE THREAD

**Issue by Amadorval75** [chemerisuk/cordova-support-google-services#15]
I have this error when i try to sync gradle for android.

Cannot add extension with name 'googleServices', as there is an extension already registered with that name.

I use cordova-firebase-plugin and cordova-plugin-firebase-analytics and I need to sync this project in order to test my app on Android.

**Comment by serkon** [comment]
I get this error when add `cordova-plugin-firebase` and `cordova-plugin-appcenter-push` plugins at the same time to my ionic cordova project. I guess These plugins uses same resource `google-services.json` files. 

It was fixed when remove `cordova-plugin-appcenter-push` also config.xml

**Comment by chemerisuk** [comment]
Fixed in v1.3.0, I will update related project to this version soon.

**Comment by devtechvalens** [comment]
Did anybody found the exact solution for the above error?
