### ISSUE TITLE
trying to install cordova-support-google-services for android

### ISSUE THREAD

**Issue by LucaTrip** [chemerisuk/cordova-support-google-services#16]
I need to enable push notification on the platform I upgraded to cordova version 7.1.0. I removed the phonegap plugin-plugin to update it to the latest release, but when I try to add it, it comes back to me

"Installing "phonegap-plugin-push" for android
Plugin dependency "cordova-support-google-services@1.1.0" already fetched, using that version.
Installing "cordova-support-google-services" for android
Android Studio project detected
....
Error: ENOENT: no such file or directory, open '/platforms/android/app/src/main/assets/www/cordova_plugins.js' "

@chemerisuk @Junker How can I remove it and re-add it correctly?

Thanks

**Comment by chemerisuk** [comment]
Use the latest version of phonegap-plugin-push
