### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by cikcoh** [chemerisuk/cordova-support-google-services#20]
I have followed the faq solution when i get error

> > Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
>    > For input string: "+"

After that,i got the following error

> * What went wrong:
> Could not resolve all dependencies for configuration ':app:debugCompileClasspath'.
> > Could not determine artifacts for com.facebook.android:facebook-common:4.39.0
>    > Could not get resource 'https://jcenter.bintray.com/com/facebook/android/facebook-common/4.39.0/facebook-common-4.39.0.aar'.
>       > Could not HEAD 'https://jcenter.bintray.com/com/facebook/android/facebook-common/4.39.0/facebook-common-4.39.0.aar'.
>          > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/99.84.87.62, d29vzk4ow07wi7.cloudfront.net/99.84.87.181, d29vzk4ow07wi7.cloudfront.net/99.84.87.80, d29vzk4ow07wi7.cloudfront.net/99.84.87.218] failed: Operation timed out (Connection timed out)
>

**Comment by askona** [comment]
@cikcoh did you found any solution?

**Comment by chemerisuk** [comment]
https://github.com/chemerisuk/cordova-support-google-services#build-error-failed-to-apply-plugin-class-comgooglegmsgoogleservicesgoogleservicesplugin
