### ISSUE TITLE
Dependency failing

### ISSUE THREAD

**Issue by 50l3r** [chemerisuk/cordova-support-google-services#24]
I have this error when i try to build:

`  Dependency failing: com.google.android.gms:play-services-stats:15.0.1 -> com.google.android.gms:play-services-basement@[
  15.0.1], but play-services-basement version was 17.0.0.`

How can i downgrade to 15.0.1 ? I try this without result:

cordova plugin add cordova-support-google-services@15.0.1

**Comment by dmitryuk** [comment]
Same issue

**Comment by dmitryuk** [comment]
I found that the code fails build
`
ext.postBuildExtras = {
    if (project.extensions.findByName('googleServices') == null) {
        // apply plugin: 'com.google.gms.google-services'
        // class must be used instead of id(string) to be able to apply plugin from non-root gradle file
        apply plugin: com.google.gms.googleservices.GoogleServicesPlugin
    }
}`

**Comment by chemerisuk** [comment]
Check your dependencies.
