### ISSUE TITLE
error Could not find org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.60-eap-25 - Missing Kotlin Maven repo

### ISSUE THREAD

**Issue by joeldhenry** [chemerisuk/cordova-support-google-services#28]
Please See:

https://github.com/chemerisuk/cordova-support-google-services/pull/26

https://github.com/chemerisuk/cordova-support-google-services/pull/27

**Comment by khaled-developer** [comment]
any solutions ?

**Comment by haisham** [comment]
much needed

**Comment by mekbeb** [comment]
Hoping to find a quick fix for this

**Comment by deliverymanager** [comment]
https://stackoverflow.com/questions/58529904/error-could-not-find-org-jetbrains-kotlinkotlin-stdlib-jdk81-3-60-eap-25-in-i

**Comment by chemerisuk** [comment]
Fixed in https://github.com/chemerisuk/cordova-support-google-services/pull/26
