### ISSUE TITLE
Invalid google_app_id on Android

### ISSUE THREAD

**Issue by gecko-8** [chemerisuk/cordova-support-google-services#3]
Hi there,
I've setup a Cordova app to use the cordova-plugin-firebase-analytics plugin (which uses this one). It's working fine for iOS but not Android. When I output the logs with adb logcat I get the following error:
`01-02 13:54:57.322 E/FA      (18325): Invalid google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI. provided id: 1046165292000`
I've added the google-services.json file from the Firebase console and added the com.google.gms plugin line to my build.gradle file (in platforms/android). I'm honestly at a loss as to what to look at next.
Thanks,
Jason

**Comment by chemerisuk** [comment]
https://github.com/chemerisuk/cordova-support-google-services#installation

**Comment by gecko-8** [comment]
That's exactly what I did.
