### ISSUE TITLE
This plugin can now be archieved

### ISSUE THREAD

**Issue by sagrawal31** [chemerisuk/cordova-support-google-services#38]
Thanks for this simple yet powerful plugin which has solved pain of many Cordova developers.

A new version of `cordova-android` (9.0.0) was released [yesterday](https://github.com/apache/cordova-android/blob/master/RELEASENOTES.md#900-jun-23-2020) which now supports a configuration `GoogleServicesVersion` which can be added in `config.xml` to enable the GoogleServicesPlugin.

So considering this new setting, this plugin can be achieved and the same can be updated & conveyed via `README.md`.

The PR- https://github.com/apache/cordova-android/pull/893/files

**Comment by chemerisuk** [comment]
This is great news indeed. I will update the repo. Can you help with the testing?

**Comment by chemerisuk** [comment]
https://github.com/chemerisuk/cordova-support-google-services/commit/5fd94d9459983409d1bd2c9eca10ec80272b1305

Patched version published as `v1.4.1`.

**Comment by sagrawal31** [comment]
That was pretty fast @chemerisuk Appreciate that. I'll be happy to test stuff.
