### ISSUE TITLE
Unable to import anything from com.google.android.gms

### ISSUE THREAD

**Issue by andreszs** [chemerisuk/cordova-support-google-services#5]
I'm trying to develop a Cordova plugin, that requires the [SafetyNet API](https://developers.google.com/android/reference/com/google/android/gms/safetynet/package-summary), but when trying to compile, the library import fails:

> error: package com.google.android.gms.safetynet does not exist

I've added this to the plugin's JAR:

`import com.google.android.gms.safetynet.SafetyNet;`

How can I correctly import this API? I've also tried installing this [older Google Play Services plugin](https://www.npmjs.com/package/cordova-plugin-googleplayservices) with the same result.

**Comment by davidgv88** [comment]
I have the same problem with the plugin https://github.com/mapsplugin/cordova-plugin-googlemaps

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/77ed0853badf01ae9f281c29bd35499d1cefb059/plugin.xml#L265
