### ISSUE TITLE
Gradle: Use cdvPluginPostBuildExtras instead of ext.postBuildExtras

### ISSUE THREAD

**Issue by merrygobyebye** [chemerisuk/cordova-support-google-services#9]
Cordova Plugins should use `cdvPluginPostBuildExtras` (https://github.com/apache/cordova-android/blob/e9750b5cabe70b1fc9abfad28fd1239d9b9415c2/bin/templates/project/app/build.gradle#L90) to have code run at the end of the build gradle script instead of `ext.postBuildExtras` (https://github.com/apache/cordova-android/blob/e9750b5cabe70b1fc9abfad28fd1239d9b9415c2/bin/templates/project/app/build.gradle#L321). When multiple plugins use `ext.postBuildExtras`, each plugin will overwrite the previous plugin's assignment of it. The offending lines of code in this plugin are here:
https://github.com/chemerisuk/cordova-support-google-services/blob/e23fc9501382ea6b760e35a051b90b3108b1a9e1/build.gradle#L15-L17

**Comment by jacobg** [comment]
Here's the entire build.gradle file, including version changes and google() repo:
```
buildscript {
    repositories {
        google()
        jcenter()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0'
        classpath 'com.google.gms:google-services:4.2.0'
    }
}

// apply plugin: 'com.google.gms.google-services'
// class must be used instead of id(string) to be able to apply plugin from non-root gradle file
ext.cdvPluginPostBuildExtras = {
    apply plugin: 'com.google.gms.google-services'
    com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true
}
```

**Comment by chemerisuk** [comment]
Merged in https://github.com/chemerisuk/cordova-support-google-services/pull/10

**Comment by davidofwatkins** [comment]
Hey guys, it looks like this (#10) was [reverted](https://github.com/chemerisuk/cordova-support-google-services/commit/959bd0ebb7718140717f4cf5c84b6d992b5b2544) to fix compatibility issues with other plugins that also try to apply `GoogleServicesPlugin`.

I'm not very familiar with Gradle, but is there any way to accommodate both those compatibility issues and this one? I've been dealing with a problem where a few different plugins are using `ext. postBuildExtras`, and it's not obvious that certain dependencies are dropped when multiple plugins step on each other like this.

**Comment by chemerisuk** [comment]
@davidofwatkins use the latest v1.3.1, compatibility improved there

**Comment by kbrownlees** [comment]
@chemerisuk it feels like the plugin could use cdvPluginPostBuildExtras again now that there are additional checks in place? Just hit this where it wasn't being run because another plugin defines ext.postBuildExtras.

**Comment by jacobg** [comment]
I think this issue is not resolved. Without replacing the build.gradle file as I wrote above, `cordova build android` fails with error: `Crashlytics found an invalid API key: null.`

Discussion on stackoverflow points to google-services configuration issue:
https://stackoverflow.com/questions/52614015/invalid-crashlytics-api-key-error-when-upgrading-to-android-gradle-plugin-3-3-0

The build.gradle file above fixes the problem.

**Comment by chemerisuk** [comment]
@jacobg FYI next version of `cordova-android` will have intergated support for the gradle plugin https://github.com/apache/cordova-android/pull/893. I don't think we should spend more time on this issue.
